//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace praktika_demo
{
    using System;
    using System.Collections.Generic;
    
    public partial class auth
    {
        public int userID { get; set; }
        public string login { get; set; }
        public string password { get; set; }
    
        public virtual user user { get; set; }
    }
}
